# Generated by Django 3.2 on 2021-04-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DoB', models.DateField()),
                ('Email', models.EmailField(max_length=60)),
                ('Phone', models.CharField(max_length=14)),
            ],
        ),
    ]
